uwb_range_topic: /nlink_linktrack_tagframe0

num_uwb: 7
# an array, the IDs of the UWB anchors (the last ID is the moving module to be localized)
AnchorId: [00, 01, 02, 03, 04, 05, 06, 07]
# an array, the postions (x, y, z) of the UWB anchors (the last three elements, is the initial postion of the moving module to be localized)
AnchorPos: [-8.1926, -8.1926, 2.77,
            -11.5862, 0, 0.5, 
            -8.1926, 8.1926, 2.77, 
            0, 11.5862, 0.5, 
            8.1926, 8.1926, 2.77, 
            11.5862, 0, 0.5, 
            8.1926, -8.1926, 2.77, 
            0, -11.5862, 0.5]
# the antenna offset on the moving module, there may be multiple antennas. DONOT SET IT IF THERE IS NO OFFSET  
antennaOffset: [-0.2, 0, 0, 0.2, 0, 0, 0, -0.1]